name: Kernel Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential clang llvm \
            bc flex bison \
            libssl-dev libelf-dev \
            libncurses-dev \
            ccache git zip

      - name: Setup clang
        run: |
          git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main clang

      - name: Build kernel
        run: |
          export PATH="$PWD/clang/bin:$PATH"
          make O=out ARCH=arm64 defconfig
          make -j$(nproc --all) \
            O=out \
            ARCH=arm64 \
            LLVM=1 LLVM_IAS=1

      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: out/arch/arm64/boot/*